// lib/lit-simple.js
import { LitElement, html } from '../web_modules/lit-element.js'

// A Simple Component
class HelloMessage extends LitElement {
  static get properties() {
    return {
      name: { type: String }
    }
  }

  render() {
    return html`
      <div>
        Hello ${this.name}
      </div>
    `
  }
}

customElements.define('hello-example', HelloMessage)
// <hello-example name=Taylor></hello-example>

// lib/react-simple.js
import React from '/web_modules/react.js'
import ReactDOM from '/web_modules/react-dom.js'
import htm from '/web_modules/htm.js'

// React + htm
const html = htm.bind(React.createElement)

// A Simple Component
class HelloMessage extends React.Component {
  render() {
    return html`
      <div>
        Hello ${this.props.name}
      </div>
    `
  }
}

ReactDOM.render(
  html`<${HelloMessage} name=Taylor />`,
  document.getElementById('hello-example')
)
// <div id=hello-example></div>
