// lib/lit-stateful.js
import { LitElement, html } from '../web_modules/lit-element.js'

// A Stateful Component
class Timer extends LitElement {
  static get properties() {
    return {
      state: { type: Object }
    }
  }

  constructor() {
    super()
    this.state = { seconds: 0 }
  }

  tick() {
    this.state = {
      seconds: this.state.seconds + 1
    }
  }

  connectedCallback() {
    super.connectedCallback()
    this.interval = setInterval(() => this.tick(), 1000)
  }

  disconnectedCallback() {
    super.disconnectedCallback()
    clearInterval(this.interval)
  }

  render() {
    return html`
      <div>
        Seconds: ${this.state.seconds}
      </div>
    `
  }
}

customElements.define('timer-example', Timer)
// <timer-example></timer-example>

// lib/react-stateful.js
import React from '../web_modules/react.js'
import ReactDOM from '../web_modules/react-dom.js'
import htm from '../web_modules/htm.js'

// React + htm
const html = htm.bind(React.createElement)

// A Stateful Component
class Timer extends React.Component {
  constructor(props) {
    super(props)
    this.state = { seconds: 0 }
  }

  tick() {
    this.setState(state => ({
      seconds: state.seconds + 1
    }))
  }

  componentDidMount() {
    this.interval = setInterval(() => this.tick(), 1000)
  }

  componentWillUnmount() {
    clearInterval(this.interval)
  }

  render() {
    return html`
      <div>
        Seconds: ${this.state.seconds}
      </div>
    `
  }
}

ReactDOM.render(
  html`<${Timer} />`,
  document.getElementById('timer-example')
)
// <div id=timer-example></div>
